# メタ設定
meta:
  # ゲームタイトル
  title: Example Game
  # 省略したゲームタイトル (ホーム画面でのアプリ名)
  shortTitle: Game
  # ゲームの短い説明文
  description: This is The Example Game.
  # アプリケーション ID (アプリデプロイに必要)
  applicationId: xxx.xxx.xxx
  # アプリバージョン
  version: 0.0.1
  # 開発者情報
  author:
    email: abc@def.com
    href: https://#your?homepage
  # 許可する外部 URL (ワイルドカード可)
  # https://*/* -> HTTPS の全てのサイト
  allow-href:
    - https://www.google.com

# ゲームエンジン設定
engine:
  # ゲーム画面の横幅
  width: 480
  # ゲーム画面の縦幅
  height: 640
  # リサイズ時にデバイス画面のどの大きさを基準に引き延ばすか
  # width -> デバイス画面の横幅に合わせる
  # height -> デバイス画面の縦幅に合わせる
  # fit -> 強制的にデバイス画面に合わせる (歪み注意)
  # none -> 合わせない (はみ出し注意)
  resize: width
  # 画面の向き
  # portrait -> 縦
  # landscape -> 横
  # all -> デバイスに連動 (はみ出し注意)
  orientation: portrait

# 環境設定
environment:
  # Android SDK 設定
  android-sdk:
    # Android SDK の場所
    path: C:\Users\{username}\AppData\Local\Android\Sdk
    # ビルドに使用する Android SDK のバージョン
    version: 30.0.3
  # AdMob 広告設定
  # テスト用のユニット ID 一覧: https://developers.google.com/admob/android/test-ads#demo_ad_units
  admob:
    # Admob を有効化するか？
    # false -> 無効にする
    # true -> 有効化する (下記のアプリ ID と ユニット ID が必要)
    enable: false
    # アプリ ID
    app-id: ca-app-pub-XXXXXXXXXXXXXXXX~XXXXXXXXXX
    # 起動時広告のユニット ID
    app-open: ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXXXXX
    # バナー広告のユニット ID
    banner: ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXXXXX
    # インタースティシャル広告のユニット ID
    interstitial: ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXXXXX
    # リワード広告のユニット ID
    rewarded: ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXXXXX
    # リワードインタースティシャル広告のユニット ID
    rewarded-interstitial: ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXXXXX
